use_frameworks!

target 'CCCustomChatModule_Example' do
  pod 'CCCustomChatModule', :path => '../'

  target 'CCCustomChatModule_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
